[package]
name = "my_test"
version = "0.1.0"
authors = ["Mohsen <flashfa8@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.7.0"
pwhash = "0.3"
serde_json = "1.0.51"
